const translations = {
  tr: { privacy:'Verileriniz cihazınızda kalır', sample:'Örnek yükle', import:'JSON içe aktar', heroTitle:"JSON'u <em>görünür</em> hale getir.", heroCopy:'Verinizi tabloya dönüştürün, yapısını keşfedin ve dışa aktarın. Hiçbir veri sunucuya gitmez.', jsonData:'JSON verisi', pasteHint:'⌘ + V ile yapıştır', view:'Görünüm', table:'▦ Tablo', listKey:'Liste anahtarı', keyPlaceholder:'örn. data', searchPlaceholder:'Sonuçlarda ara...', columns:'▤ Kolonlar', expand:'＋ Aç', collapse:'− Kapat', copy:'⧉ Kopyala', downloadCsv:'↧ CSV indir' },
  en: { privacy:'Your data stays on your device', sample:'Load sample', import:'Import JSON', heroTitle:'Make JSON <em>visible</em>.', heroCopy:'Turn your data into a table, explore its structure, and export it. Nothing leaves your browser.', jsonData:'JSON data', pasteHint:'⌘ + V to paste', view:'View', table:'▦ Table', listKey:'List key', keyPlaceholder:'e.g. data', searchPlaceholder:'Search results...', columns:'▤ Columns', expand:'＋ Expand', collapse:'− Collapse', copy:'⧉ Copy', downloadCsv:'↧ Download CSV' }
};
let language = localStorage.getItem('jsonlens-language') || 'tr';
function applyLanguage() { document.documentElement.lang = language; document.querySelectorAll('[data-i18n]').forEach(element => { const value = translations[language][element.dataset.i18n]; if (element.id === 'heroTitle') element.innerHTML = value; else element.textContent = value; }); document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = translations[language][element.dataset.i18nPlaceholder]; }); document.querySelector('#languageSelect').value = language; document.title = language === 'en' ? 'JsonLens — Make JSON visible' : "JsonLens — JSON'u sadeleştir"; if (parsed !== null) render(); }
const sample = `{
  "project": "JsonLens",
  "version": 1,
  "features": [
    { "name": "Tree görünümü", "active": true },
    { "name": "CSV dışa aktarma", "active": true }
  ],
  "owner": { "name": "Ada Lovelace", "role": "Builder" }
}`;
const input = document.querySelector('#jsonInput');
const output = document.querySelector('#output');
const lineNumbers = document.querySelector('#lineNumbers');
const statusText = document.querySelector('#statusText');
const rowCount = document.querySelector('#rowCount');
const charCount = document.querySelector('#charCount');
const listKey = document.querySelector('#listKey');
const statsPanel = document.querySelector('#statsPanel');
let parsed = null;
let activeView = 'table';
let selectedColumns = null;
const columnWidths = {};
let toastTimer;

function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2200); }
function updateEditorMeta() { const lines = input.value.split('\n').length; lineNumbers.innerHTML = Array.from({ length: lines }, (_, i) => i + 1).join('<br>'); charCount.textContent = `${input.value.length.toLocaleString('tr-TR')} karakter`; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char])); }
function valueHtml(value) { if (value === null) return '<span class="value-null">null</span>'; if (typeof value === 'boolean') return `<span class="value-boolean">${value}</span>`; if (typeof value === 'number') return `<span class="value-number">${value}</span>`; if (Array.isArray(value)) return `<details class="inline-list"><summary>${value.length} öğe</summary><div class="list-items">${value.map((item, index) => `<div><span class="list-index">${index + 1}</span>${valueHtml(item)}</div>`).join('')}</div></details>`; if (typeof value === 'object') return `<details class="inline-list"><summary>${Object.keys(value).length} alan</summary><div class="list-items">${Object.entries(value).map(([key, item]) => `<div><span class="list-key">${escapeHtml(key)}</span>${valueHtml(item)}</div>`).join('')}</div></details>`; return escapeHtml(value); }
function readListValue(data) { const key = listKey.value.trim(); if (!key) return data; const readPath = (value, parts) => { if (value == null) return undefined; if (!parts.length) return value; if (Array.isArray(value)) { const results = value.flatMap(item => { const result = readPath(item, parts); return result === undefined ? [] : Array.isArray(result) ? result : [result]; }); return results; } return readPath(value[parts[0]], parts.slice(1)); }; return readPath(data, key.split('.')); }
function flattenRows(data) { const listValue = readListValue(data); if (Array.isArray(listValue)) return listValue.every(item => item && typeof item === 'object' && !Array.isArray(item)) ? listValue : listValue.map((value, index) => ({ index, value })); if (listValue === undefined) return []; if (listValue && typeof listValue === 'object') return [listValue]; return [{ value: listValue }]; }
function syncSelectedColumns(keys) { if (selectedColumns === null) selectedColumns = new Set(keys); else selectedColumns = new Set([...selectedColumns, ...keys].filter(key => keys.includes(key))); return keys.filter(key => selectedColumns.has(key)); }
function renderColumnPicker(keys) { const panel = document.querySelector('#columnsPanel'); const labels = language === 'en' ? { title:'Visible columns', all:'Show all' } : { title:'Görünen kolonlar', all:'Tümünü göster' }; panel.innerHTML = `<div class="columns-heading"><strong>${labels.title}</strong><button type="button" id="showAllColumns">${labels.all}</button></div><div class="columns-options">${keys.map(key => `<label><input type="checkbox" value="${escapeHtml(key)}" ${selectedColumns.has(key) ? 'checked' : ''}><span>${escapeHtml(key)}</span></label>`).join('')}</div>`; panel.querySelectorAll('input').forEach(input => input.addEventListener('change', event => { if (!event.target.checked && selectedColumns.size === 1) { event.target.checked = true; return showToast(language === 'en' ? 'Keep at least one column visible.' : 'En az bir kolon görünür kalmalı.'); } selectedColumns[event.target.checked ? 'add' : 'delete'](event.target.value); render(); })); panel.querySelector('#showAllColumns').addEventListener('click', () => { selectedColumns = new Set(keys); render(); }); }
function bindColumnResize() { document.querySelectorAll('.column-resizer').forEach(resizer => resizer.addEventListener('pointerdown', event => { event.preventDefault(); const header = event.target.closest('th'); const key = header.dataset.key; const startX = event.clientX; const startWidth = header.offsetWidth; const move = moveEvent => { columnWidths[key] = Math.max(90, Math.min(600, startWidth + moveEvent.clientX - startX)); header.style.width = `${columnWidths[key]}px`; }; const stop = () => { document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', stop); }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', stop); })); }
function renderTable(data, query = '') { const rows = flattenRows(data); const keys = [...new Set(rows.flatMap(row => Object.keys(row)))]; const visibleKeys = syncSelectedColumns(keys); renderColumnPicker(keys); const filtered = query ? rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase())) : rows; if (!keys.length || !visibleKeys.length) return `<div class="empty-state"><b>Tabloya dönüştürülemedi</b>Bu veri yapısı kolon içermiyor.</div>`; return `<div class="table-scroll"><table class="json-table"><colgroup>${visibleKeys.map(key => `<col style="${columnWidths[key] ? `width:${columnWidths[key]}px` : ''}">`).join('')}</colgroup><thead><tr>${visibleKeys.map(key => `<th data-key="${escapeHtml(key)}" style="${columnWidths[key] ? `width:${columnWidths[key]}px` : ''}">${escapeHtml(key)}<span class="column-resizer" title="${language === 'en' ? 'Resize column' : 'Kolon genişliğini değiştir'}"></span></th>`).join('')}</tr></thead><tbody>${filtered.map(row => `<tr>${visibleKeys.map(key => `<td>${valueHtml(row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function statValue(value) { if (value === null) return 'null'; if (value && typeof value === 'object') return JSON.stringify(value); return String(value); }
function renderStats(column) { const rows = flattenRows(parsed); const values = rows.flatMap(row => { const value = row[column]; return Array.isArray(value) ? value.flat(Infinity) : [value]; }); const counts = new Map(); values.forEach(value => { const label = statValue(value); counts.set(label, (counts.get(label) || 0) + 1); }); const topValues = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, 10); const english = language === 'en'; const labels = english ? { title:'COLUMN STATISTICS · LIST VALUES', unique:'unique values', rows:'total rows', values:'total values', close:'Close statistics' } : { title:'KOLON İSTATİSTİĞİ · LİSTE DEĞERLERİ', unique:'unique değer', rows:'toplam satır', values:'toplam değer', close:'İstatistikleri kapat' }; statsPanel.hidden = false; statsPanel.innerHTML = `<div class="stats-heading"><div><span class="stats-label">${labels.title}</span><strong>${escapeHtml(column)}</strong></div><button class="stats-close" aria-label="${labels.close}">×</button></div><div class="stats-summary"><span><b>${counts.size}</b> ${labels.unique}</span><span><b>${rows.length}</b> ${labels.rows}</span><span><b>${values.length}</b> ${labels.values}</span></div><div class="stats-list">${topValues.map(([value, count], index) => `<div class="stats-row"><span class="stats-rank">${index + 1}</span><span class="stats-value" title="${escapeHtml(value)}">${escapeHtml(value)}</span><span class="stats-count">${count}</span><span class="stats-bar" style="--bar:${Math.round(count / values.length * 100)}%"></span></div>`).join('')}</div>`; statsPanel.querySelector('.stats-close').addEventListener('click', () => { statsPanel.hidden = true; }); }
function nodeHtml(value, key = 'root', depth = 0) { const object = value && typeof value === 'object'; const id = `node-${Math.random().toString(36).slice(2)}`; if (!object) return `<div class="tree-node"><div class="tree-row"><span style="width:16px"></span><span class="tree-key">${escapeHtml(key)}</span><span>:</span><span class="tree-value">${valueHtml(value)}</span></div></div>`; const entries = Object.entries(value); return `<div class="tree-node" data-depth="${depth}"><div class="tree-row"><button class="tree-toggle" data-target="${id}">⌄</button><span class="tree-key">${escapeHtml(key)}</span><span>:</span><span class="tree-type">${Array.isArray(value) ? `Array · ${entries.length}` : `Object · ${entries.length}`}</span></div><div class="tree-children" id="${id}">${entries.map(([childKey, childValue]) => nodeHtml(childValue, childKey, depth + 1)).join('')}</div></div>`; }
function render() { if (parsed === null) { output.innerHTML = '<div class="empty-state"><b>Henüz JSON yok</b>Sol tarafa JSON yapıştırarak başlayın.</div>'; statusText.textContent = 'JSON bekleniyor'; rowCount.textContent = ''; statsPanel.hidden = true; return; } const listValue = readListValue(parsed); if (listKey.value.trim() && listValue === undefined) { output.innerHTML = `<div class="empty-state"><b>Liste anahtarı bulunamadı</b><span>“${escapeHtml(listKey.value.trim())}” için bir dizi veya nesne bulunamadı.</span></div>`; statusText.textContent = 'Anahtar bulunamadı'; rowCount.textContent = ''; statsPanel.hidden = true; return; } const query = document.querySelector('#searchInput').value; output.innerHTML = activeView === 'table' ? renderTable(parsed, query) : `<div class="tree">${nodeHtml(listKey.value.trim() ? listValue : parsed, listKey.value.trim() || 'root')}</div>`; const columnsPanel = document.querySelector('#columnsPanel'); columnsPanel.hidden = activeView !== 'table' || !flattenRows(parsed).length; document.querySelector('#columnsBtn').hidden = activeView !== 'table'; statusText.textContent = listKey.value.trim() ? `Liste: ${listKey.value.trim()}` : 'JSON listesi'; rowCount.textContent = `${flattenRows(parsed).length} satır`; output.querySelectorAll('.json-table th').forEach(header => header.addEventListener('click', event => { if (!event.target.classList.contains('column-resizer')) renderStats(header.dataset.key); })); bindColumnResize(); output.querySelectorAll('.tree-toggle').forEach(button => button.addEventListener('click', () => { const target = document.getElementById(button.dataset.target); const closed = target.style.display === 'none'; target.style.display = closed ? '' : 'none'; button.textContent = closed ? '⌄' : '›'; })); }
function parseInput() { updateEditorMeta(); try { parsed = JSON.parse(input.value); render(); } catch (error) { parsed = null; statusText.textContent = 'JSON formatı hatalı'; rowCount.textContent = ''; output.innerHTML = `<div class="empty-state"><b>JSON okunamadı</b><span>${escapeHtml(error.message)}</span></div>`; } }
function downloadCsv() { if (parsed === null) return showToast('Önce geçerli bir JSON girin.'); const rows = flattenRows(parsed); if (!rows.length) return showToast('Dışa aktarılacak liste bulunamadı.'); const keys = [...new Set(rows.flatMap(row => Object.keys(row)))]; const csv = [keys, ...rows.map(row => keys.map(key => { const value = row[key]; const text = value && typeof value === 'object' ? JSON.stringify(value) : String(value ?? ''); return `"${text.replaceAll('"', '""')}"`; }))].map(row => row.join(',')).join('\n'); const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'jsonlens-export.csv'; link.click(); URL.revokeObjectURL(url); showToast('CSV dosyası indirildi.'); }
input.addEventListener('input', parseInput); listKey.addEventListener('input', render); document.querySelector('#searchInput').addEventListener('input', render); document.querySelector('#languageSelect').addEventListener('change', event => { language = event.target.value; localStorage.setItem('jsonlens-language', language); applyLanguage(); }); document.querySelector('#loadSampleBtn').addEventListener('click', () => { input.value = sample; parseInput(); showToast(language === 'en' ? 'Sample JSON loaded.' : 'Örnek JSON yüklendi.'); }); document.querySelector('#clearBtn').addEventListener('click', () => { input.value = ''; parsed = null; parseInput(); }); document.querySelector('#exportBtn').addEventListener('click', downloadCsv); document.querySelector('#copyBtn').addEventListener('click', async () => { if (!input.value) return showToast(language === 'en' ? 'There is no JSON to copy.' : 'Kopyalanacak JSON yok.'); await navigator.clipboard.writeText(input.value); showToast(language === 'en' ? 'JSON copied to clipboard.' : 'JSON panoya kopyalandı.'); }); document.querySelectorAll('.view-tab').forEach(tab => tab.addEventListener('click', () => { activeView = tab.dataset.view; document.querySelectorAll('.view-tab').forEach(item => item.classList.toggle('active', item === tab)); render(); })); document.querySelector('#expandBtn').addEventListener('click', () => { output.querySelectorAll('.tree-children').forEach(node => node.style.display = ''); output.querySelectorAll('.tree-toggle').forEach(button => button.textContent = '⌄'); }); document.querySelector('#collapseBtn').addEventListener('click', () => { output.querySelectorAll('.tree-children').forEach(node => node.style.display = 'none'); output.querySelectorAll('.tree-toggle').forEach(button => button.textContent = '›'); }); document.querySelector('#fileInput').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { input.value = reader.result; parseInput(); showToast(language === 'en' ? 'JSON file loaded.' : 'JSON dosyası yüklendi.'); }; reader.readAsText(file); }); document.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.querySelector('#searchInput').focus(); } });
document.querySelector('#columnsBtn').addEventListener('click', () => { const panel = document.querySelector('#columnsPanel'); panel.hidden = !panel.hidden; document.querySelector('#columnsBtn').setAttribute('aria-expanded', String(!panel.hidden)); });
applyLanguage();
parseInput();
